version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  pre_build:
    commands:
      - export STARTTIME=`date +%s`
      - export BUILDNAME="$GIT_BRANCH-`date +%Y-%m-%d`"
      - export BRANCH="$GIT_BRANCH"
      - export SOURCE_VERSION="$CODEBUILD_SOURCE_VERSION"
      - export FUNCTION_NAME="$LAMBDA_TO_UPDATE"
      - export username="$GITUSER"
      - export pass="$GITPASSWORD"
      - echo "BRANCH $BRANCH"
      - echo "SOURCE_VERSION $SOURCE_VERSION"
      
  build:
    commands:
      - echo Build started on `date`
      - aws s3 sync . s3://datasync-test1212/
      - test=$(aws datasync create-location-efs --subdirectory /sapper/ --efs-filesystem-arn 'arn:aws:elasticfilesystem:us-east-1:916127912776:file-system/fs-72480987' --ec2-config SecurityGroupArns='arn:aws:ec2:us-east-1:916127912776:security-group/sg-075b1f5dded812045',SubnetArn='arn:aws:ec2:us-east-1:916127912776:subnet/subnet-0a0331d3800b5ef7a' --region us-east-1 | awk 'NF{ print $NF }' | sed 's/{//g' | sed 's/"//g' | sed 's/}//g')
      - sleep 3
      - echo $test
        #aws lambda update-function-code --function-name test1 --s3-bucket test-buildartifactsbucket --s3-key source.zip
      - echo "buhhhhhfesferdsfdsfhhl"
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
