version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Build started on `date`
      - ls
      - rm -rf *
      - ls
      - pwd
      - git clone https://github.com/nandinired/nandini.git --branch v1.0
      - mv nandini/* .
      - rm -rf nandini
      - ls
      - export BUCKET=$BUILD_OUTPUT_BUCKET
      - echo $BUCKET
      - echo $BUILD_OUTPUT_BUCKET
      - pip install dirsync
      - zip -qr source.zip ./
      - aws s3 cp ./*.zip s3://$BUILD_OUTPUT_BUCKET
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
      - mkdir build-output
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
