version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Build started on `date`
      - cd ..
      - rm -rf test 
      - git clone https://github.com/nandinired/nandini.git --branch v1.0
      - ls
      - cd nandini
      - export BUCKET=test-pipeline-output1-bucket
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
      - mkdir build-output
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
