version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python --version
  pre_build:
    commands:
      - export STARTTIME=`date +%s`
      - export BUILDNAME="$GIT_BRANCH-`date +%Y-%m-%d`"
      - export BRANCH="$GIT_BRANCH"
      - export SOURCE_VERSION="$CODEBUILD_SOURCE_VERSION"
      - export FUNCTION_NAME="$LAMBDA_TO_UPDATE"
      - export username="$GITUSER"
      - export pass="$GITPASSWORD"
      - echo "BRANCH $BRANCH"
      - echo "SOURCE_VERSION $SOURCE_VERSION"
  build:
    commands:
      - echo Build started on `date`
      - ls
      - git status
      - pwd
      - pip install dirsync
      - cp -p -r --backup=numbered `find ~/ -name dirsync -a -type d` ./
      - ls
      - ls
      - ls
      - echo "SOURCE_VERSION $SOURCE_VERSION"
      - echo "SOURCE_VERSION $SOURCE_VERSION"
      - zip -qr source.zip ./
      - aws lambda update-function-code --function-name test --s3-bucket test-buildartifactsbucket --s3-key source.zip
      - sleep 3
      - aws s3 rm s3://test-buildartifactsbucket/ --recursive
      #- aws sns publish {} topic
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'

