version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo Build started on `date`
      - cd /Users/nand8468/personal/tests
      - git clone https://github.com/nandinired/nandini.git 
      - echo Compiling the Python code...
      - pip install requests -t .
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
