version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python --version
  pre_build:
    commands:
      - export STARTTIME=`date +%s`
      - export BUILDNAME="$GIT_BRANCH-`date +%Y-%m-%d`"
      - export BRANCH="$GIT_BRANCH"
      - export SOURCE_VERSION="$CODEBUILD_SOURCE_VERSION"
      - export FUNCTION_NAME="$LAMBDA_TO_UPDATE"
      - export username="$GITUSER"
      - export pass="$GITPASSWORD"
      - echo "BRANCH $BRANCH"
      - echo "SOURCE_VERSION $SOURCE_VERSION"
      
  build:
    commands:
      - echo Build started on `date`
      - ls
      - pwd
      - pip install dirsync
      - aws s3 rm s3://test-buildartifactsbucket/testing --recursive
      - sleep 3
      - aws s3 sync . s3://test-buildartifactsbucket/testing
      - sleep 3
      
        #aws lambda update-function-code --function-name test1 --s3-bucket test-buildartifactsbucket --s3-key source.zip
      - echo "buhhhhhfesferdsfdsfhhl"
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
