AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Parameters:
  SecurityGroupIds:
    Type: CommaDelimitedList
    Description: The list of securitysg
  SubnetIDs:
    Type: CommaDelimitedList
    Description: The list of SubnetIDs in your Virtual Private Cloud (VPC)
  Arn:
    Type: String
    Description: The arn of the EFS
  Function:
    Type: String
    Description: The name of the Lambda
  Role:
    Type: String
    Description: The role to access EFS from Lambda
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref Function
      Handler: index.lambda_handler
      CodeUri: ./
      VpcConfig:
        SubnetIds: !Ref SubnetIDs
        SecurityGroupIds: !Ref SecurityGroupIds
      Runtime: python3.8
      Role: !Ref Role
      FileSystemConfigs:
        - Arn: !Ref Arn
          LocalMountPath: /mnt/src
