AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Outputs:
  LambdaFunction:
    Description: Lambda Function
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunction'
    Value: !GetAtt 
      - LambdaFunction
      - Arn
  LambdaFunctionName:
    Description: Lambda Function Name
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionName'
    Value: !Ref LambdaFunction
Parameters:
  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: sg-0af805e4069311e89
  RoleARN:
    Type: String
    Description: Role ARN
    Default: arn:aws:iam::402783855041:role/lambda_efs
  SubnetIDs:
    Type: CommaDelimitedList
    Description: The list of SubnetIDs in your Virtual Private Cloud (VPC)
    Default: subnet-082c40be8b2e02b85
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.lambda_handler
      CodeUri: ./
      VpcConfig:
        SubnetIds: !Ref SubnetIDs
        SecurityGroupIds: !Ref SecurityGroupIds
      Runtime: python3.8
      Role: !Ref RoleARN
      FileSystemConfigs:
        - Arn: >-
            arn:aws:elasticfilesystem:us-east-2:402783855041:access-point/fsap-02ae2bf0e3760dc3e
          LocalMountPath: /mnt/access
       Events:
         MyTimeApi:
           Type: Api
           Properties:
             Path: /TimeResource
             Method: GET
