AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Parameters:
  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: sg-0af805e4069311e89
  RoleARN:
    Type: String
    Description: Role ARN
    Default: arn:aws:iam::402783855041:role/lambda_efs
  SubnetIDs:
    Type: CommaDelimitedList
    Description: The list of SubnetIDs in your Virtual Private Cloud (VPC)
    Default: subnet-082c40be8b2e02b85
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Sub '${AWS::StackName}-EFSLambda
      Handler: index.lambda_handler
      CodeUri: ./
      VpcConfig:
        SubnetIds: !Ref SubnetIDs
        SecurityGroupIds: !Ref SecurityGroupIds
      Runtime: python3.8
      Role: !Ref RoleARN
      FileSystemConfigs:
        - Arn: >-
            arn:aws:elasticfilesystem:us-east-2:402783855041:access-point/fsap-0f0cc4ffd1b228fab
          LocalMountPath: /mnt/access
