version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Start build phase `date`
      - ls
      - echo zip Source code to file=$ARTIFACT_OBJECT and upload it to bucket=$BUILD_OUTPUT_BUCKET
      - zip -qr source.zip ./
      - aws s3 cp $CODEBUILD_SRC_DIR/$ARTIFACT_OBJECT s3://$ARTIFACT_BUCKET/$BUILD_OUTPUT_BUCKET

