version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Start build phase `date`
      -	git clone https://github.com/nandinired/nandini.git --branch v1.0
      - mv nandini/* .
      - rm -rf nandini
      - ls
      - export BUCKET=$BUILD_OUTPUT_BUCKET
